/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package uk.gov.companieshouse.document.generator.core.document.models;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DocumentGenerationFailed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5835919595678364854L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentGenerationFailed\",\"namespace\":\"uk.gov.companieshouse.document.generator.core.document.models\",\"fields\":[{\"name\":\"requester_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"description_identifier\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description_values\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DescriptionValues\",\"fields\":[{\"name\":\"date\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String requester_id;
  @Deprecated public java.lang.String description;
  @Deprecated public java.lang.String description_identifier;
  @Deprecated public java.lang.String id;
  @Deprecated public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues description_values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentGenerationFailed() {}

  /**
   * All-args constructor.
   * @param requester_id The new value for requester_id
   * @param description The new value for description
   * @param description_identifier The new value for description_identifier
   * @param id The new value for id
   * @param description_values The new value for description_values
   */
  public DocumentGenerationFailed(java.lang.String requester_id, java.lang.String description, java.lang.String description_identifier, java.lang.String id, uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues description_values) {
    this.requester_id = requester_id;
    this.description = description;
    this.description_identifier = description_identifier;
    this.id = id;
    this.description_values = description_values;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requester_id;
    case 1: return description;
    case 2: return description_identifier;
    case 3: return id;
    case 4: return description_values;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requester_id = (java.lang.String)value$; break;
    case 1: description = (java.lang.String)value$; break;
    case 2: description_identifier = (java.lang.String)value$; break;
    case 3: id = (java.lang.String)value$; break;
    case 4: description_values = (uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'requester_id' field.
   * @return The value of the 'requester_id' field.
   */
  public java.lang.String getRequesterId() {
    return requester_id;
  }

  /**
   * Sets the value of the 'requester_id' field.
   * @param value the value to set.
   */
  public void setRequesterId(java.lang.String value) {
    this.requester_id = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'description_identifier' field.
   * @return The value of the 'description_identifier' field.
   */
  public java.lang.String getDescriptionIdentifier() {
    return description_identifier;
  }

  /**
   * Sets the value of the 'description_identifier' field.
   * @param value the value to set.
   */
  public void setDescriptionIdentifier(java.lang.String value) {
    this.description_identifier = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'description_values' field.
   * @return The value of the 'description_values' field.
   */
  public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues getDescriptionValues() {
    return description_values;
  }

  /**
   * Sets the value of the 'description_values' field.
   * @param value the value to set.
   */
  public void setDescriptionValues(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues value) {
    this.description_values = value;
  }

  /**
   * Creates a new DocumentGenerationFailed RecordBuilder.
   * @return A new DocumentGenerationFailed RecordBuilder
   */
  public static uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder newBuilder() {
    return new uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder();
  }

  /**
   * Creates a new DocumentGenerationFailed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentGenerationFailed RecordBuilder
   */
  public static uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder newBuilder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder other) {
    return new uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder(other);
  }

  /**
   * Creates a new DocumentGenerationFailed RecordBuilder by copying an existing DocumentGenerationFailed instance.
   * @param other The existing instance to copy.
   * @return A new DocumentGenerationFailed RecordBuilder
   */
  public static uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder newBuilder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed other) {
    return new uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder(other);
  }

  /**
   * RecordBuilder for DocumentGenerationFailed instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentGenerationFailed>
    implements org.apache.avro.data.RecordBuilder<DocumentGenerationFailed> {

    private java.lang.String requester_id;
    private java.lang.String description;
    private java.lang.String description_identifier;
    private java.lang.String id;
    private uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues description_values;
    private uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.Builder description_valuesBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requester_id)) {
        this.requester_id = data().deepCopy(fields()[0].schema(), other.requester_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description_identifier)) {
        this.description_identifier = data().deepCopy(fields()[2].schema(), other.description_identifier);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.description_values)) {
        this.description_values = data().deepCopy(fields()[4].schema(), other.description_values);
        fieldSetFlags()[4] = true;
      }
      if (other.hasDescriptionValuesBuilder()) {
        this.description_valuesBuilder = uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.newBuilder(other.getDescriptionValuesBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentGenerationFailed instance
     * @param other The existing instance to copy.
     */
    private Builder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.requester_id)) {
        this.requester_id = data().deepCopy(fields()[0].schema(), other.requester_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description_identifier)) {
        this.description_identifier = data().deepCopy(fields()[2].schema(), other.description_identifier);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.description_values)) {
        this.description_values = data().deepCopy(fields()[4].schema(), other.description_values);
        fieldSetFlags()[4] = true;
      }
      this.description_valuesBuilder = null;
    }

    /**
      * Gets the value of the 'requester_id' field.
      * @return The value.
      */
    public java.lang.String getRequesterId() {
      return requester_id;
    }

    /**
      * Sets the value of the 'requester_id' field.
      * @param value The value of 'requester_id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder setRequesterId(java.lang.String value) {
      validate(fields()[0], value);
      this.requester_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requester_id' field has been set.
      * @return True if the 'requester_id' field has been set, false otherwise.
      */
    public boolean hasRequesterId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requester_id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder clearRequesterId() {
      requester_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder setDescription(java.lang.String value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description_identifier' field.
      * @return The value.
      */
    public java.lang.String getDescriptionIdentifier() {
      return description_identifier;
    }

    /**
      * Sets the value of the 'description_identifier' field.
      * @param value The value of 'description_identifier'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder setDescriptionIdentifier(java.lang.String value) {
      validate(fields()[2], value);
      this.description_identifier = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description_identifier' field has been set.
      * @return True if the 'description_identifier' field has been set, false otherwise.
      */
    public boolean hasDescriptionIdentifier() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description_identifier' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder clearDescriptionIdentifier() {
      description_identifier = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder setId(java.lang.String value) {
      validate(fields()[3], value);
      this.id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder clearId() {
      id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'description_values' field.
      * @return The value.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues getDescriptionValues() {
      return description_values;
    }

    /**
      * Sets the value of the 'description_values' field.
      * @param value The value of 'description_values'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder setDescriptionValues(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues value) {
      validate(fields()[4], value);
      this.description_valuesBuilder = null;
      this.description_values = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'description_values' field has been set.
      * @return True if the 'description_values' field has been set, false otherwise.
      */
    public boolean hasDescriptionValues() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'description_values' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.Builder getDescriptionValuesBuilder() {
      if (description_valuesBuilder == null) {
        if (hasDescriptionValues()) {
          setDescriptionValuesBuilder(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.newBuilder(description_values));
        } else {
          setDescriptionValuesBuilder(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.newBuilder());
        }
      }
      return description_valuesBuilder;
    }

    /**
     * Sets the Builder instance for the 'description_values' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder setDescriptionValuesBuilder(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.Builder value) {
      clearDescriptionValues();
      description_valuesBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'description_values' field has an active Builder instance
     * @return True if the 'description_values' field has an active Builder instance
     */
    public boolean hasDescriptionValuesBuilder() {
      return description_valuesBuilder != null;
    }

    /**
      * Clears the value of the 'description_values' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationFailed.Builder clearDescriptionValues() {
      description_values = null;
      description_valuesBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public DocumentGenerationFailed build() {
      try {
        DocumentGenerationFailed record = new DocumentGenerationFailed();
        record.requester_id = fieldSetFlags()[0] ? this.requester_id : (java.lang.String) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.String) defaultValue(fields()[1]);
        record.description_identifier = fieldSetFlags()[2] ? this.description_identifier : (java.lang.String) defaultValue(fields()[2]);
        record.id = fieldSetFlags()[3] ? this.id : (java.lang.String) defaultValue(fields()[3]);
        if (description_valuesBuilder != null) {
          record.description_values = this.description_valuesBuilder.build();
        } else {
          record.description_values = fieldSetFlags()[4] ? this.description_values : (uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues) defaultValue(fields()[4]);
        }
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
