/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package uk.gov.companieshouse.document.generator.core.document.models;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DocumentGenerationCompleted extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5788643649444527069L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentGenerationCompleted\",\"namespace\":\"uk.gov.companieshouse.document.generator.core.document.models\",\"fields\":[{\"name\":\"requester_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description_identifier\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"document_created_at\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description_values\",\"type\":{\"type\":\"record\",\"name\":\"DescriptionValues\",\"fields\":[{\"name\":\"date\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"location\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"document_size\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String requester_id;
  @Deprecated public java.lang.String id;
  @Deprecated public java.lang.String description;
  @Deprecated public java.lang.String description_identifier;
  @Deprecated public java.lang.String document_created_at;
  @Deprecated public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues description_values;
  @Deprecated public java.lang.String location;
  @Deprecated public java.lang.String document_size;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentGenerationCompleted() {}

  /**
   * All-args constructor.
   * @param requester_id The new value for requester_id
   * @param id The new value for id
   * @param description The new value for description
   * @param description_identifier The new value for description_identifier
   * @param document_created_at The new value for document_created_at
   * @param description_values The new value for description_values
   * @param location The new value for location
   * @param document_size The new value for document_size
   */
  public DocumentGenerationCompleted(java.lang.String requester_id, java.lang.String id, java.lang.String description, java.lang.String description_identifier, java.lang.String document_created_at, uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues description_values, java.lang.String location, java.lang.String document_size) {
    this.requester_id = requester_id;
    this.id = id;
    this.description = description;
    this.description_identifier = description_identifier;
    this.document_created_at = document_created_at;
    this.description_values = description_values;
    this.location = location;
    this.document_size = document_size;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requester_id;
    case 1: return id;
    case 2: return description;
    case 3: return description_identifier;
    case 4: return document_created_at;
    case 5: return description_values;
    case 6: return location;
    case 7: return document_size;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requester_id = (java.lang.String)value$; break;
    case 1: id = (java.lang.String)value$; break;
    case 2: description = (java.lang.String)value$; break;
    case 3: description_identifier = (java.lang.String)value$; break;
    case 4: document_created_at = (java.lang.String)value$; break;
    case 5: description_values = (uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues)value$; break;
    case 6: location = (java.lang.String)value$; break;
    case 7: document_size = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'requester_id' field.
   * @return The value of the 'requester_id' field.
   */
  public java.lang.String getRequesterId() {
    return requester_id;
  }

  /**
   * Sets the value of the 'requester_id' field.
   * @param value the value to set.
   */
  public void setRequesterId(java.lang.String value) {
    this.requester_id = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'description_identifier' field.
   * @return The value of the 'description_identifier' field.
   */
  public java.lang.String getDescriptionIdentifier() {
    return description_identifier;
  }

  /**
   * Sets the value of the 'description_identifier' field.
   * @param value the value to set.
   */
  public void setDescriptionIdentifier(java.lang.String value) {
    this.description_identifier = value;
  }

  /**
   * Gets the value of the 'document_created_at' field.
   * @return The value of the 'document_created_at' field.
   */
  public java.lang.String getDocumentCreatedAt() {
    return document_created_at;
  }

  /**
   * Sets the value of the 'document_created_at' field.
   * @param value the value to set.
   */
  public void setDocumentCreatedAt(java.lang.String value) {
    this.document_created_at = value;
  }

  /**
   * Gets the value of the 'description_values' field.
   * @return The value of the 'description_values' field.
   */
  public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues getDescriptionValues() {
    return description_values;
  }

  /**
   * Sets the value of the 'description_values' field.
   * @param value the value to set.
   */
  public void setDescriptionValues(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues value) {
    this.description_values = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.String value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'document_size' field.
   * @return The value of the 'document_size' field.
   */
  public java.lang.String getDocumentSize() {
    return document_size;
  }

  /**
   * Sets the value of the 'document_size' field.
   * @param value the value to set.
   */
  public void setDocumentSize(java.lang.String value) {
    this.document_size = value;
  }

  /**
   * Creates a new DocumentGenerationCompleted RecordBuilder.
   * @return A new DocumentGenerationCompleted RecordBuilder
   */
  public static uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder newBuilder() {
    return new uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder();
  }

  /**
   * Creates a new DocumentGenerationCompleted RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentGenerationCompleted RecordBuilder
   */
  public static uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder newBuilder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder other) {
    return new uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder(other);
  }

  /**
   * Creates a new DocumentGenerationCompleted RecordBuilder by copying an existing DocumentGenerationCompleted instance.
   * @param other The existing instance to copy.
   * @return A new DocumentGenerationCompleted RecordBuilder
   */
  public static uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder newBuilder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted other) {
    return new uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder(other);
  }

  /**
   * RecordBuilder for DocumentGenerationCompleted instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentGenerationCompleted>
    implements org.apache.avro.data.RecordBuilder<DocumentGenerationCompleted> {

    private java.lang.String requester_id;
    private java.lang.String id;
    private java.lang.String description;
    private java.lang.String description_identifier;
    private java.lang.String document_created_at;
    private uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues description_values;
    private uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.Builder description_valuesBuilder;
    private java.lang.String location;
    private java.lang.String document_size;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requester_id)) {
        this.requester_id = data().deepCopy(fields()[0].schema(), other.requester_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description_identifier)) {
        this.description_identifier = data().deepCopy(fields()[3].schema(), other.description_identifier);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.document_created_at)) {
        this.document_created_at = data().deepCopy(fields()[4].schema(), other.document_created_at);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.description_values)) {
        this.description_values = data().deepCopy(fields()[5].schema(), other.description_values);
        fieldSetFlags()[5] = true;
      }
      if (other.hasDescriptionValuesBuilder()) {
        this.description_valuesBuilder = uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.newBuilder(other.getDescriptionValuesBuilder());
      }
      if (isValidValue(fields()[6], other.location)) {
        this.location = data().deepCopy(fields()[6].schema(), other.location);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.document_size)) {
        this.document_size = data().deepCopy(fields()[7].schema(), other.document_size);
        fieldSetFlags()[7] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentGenerationCompleted instance
     * @param other The existing instance to copy.
     */
    private Builder(uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.requester_id)) {
        this.requester_id = data().deepCopy(fields()[0].schema(), other.requester_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description_identifier)) {
        this.description_identifier = data().deepCopy(fields()[3].schema(), other.description_identifier);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.document_created_at)) {
        this.document_created_at = data().deepCopy(fields()[4].schema(), other.document_created_at);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.description_values)) {
        this.description_values = data().deepCopy(fields()[5].schema(), other.description_values);
        fieldSetFlags()[5] = true;
      }
      this.description_valuesBuilder = null;
      if (isValidValue(fields()[6], other.location)) {
        this.location = data().deepCopy(fields()[6].schema(), other.location);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.document_size)) {
        this.document_size = data().deepCopy(fields()[7].schema(), other.document_size);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'requester_id' field.
      * @return The value.
      */
    public java.lang.String getRequesterId() {
      return requester_id;
    }

    /**
      * Sets the value of the 'requester_id' field.
      * @param value The value of 'requester_id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setRequesterId(java.lang.String value) {
      validate(fields()[0], value);
      this.requester_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requester_id' field has been set.
      * @return True if the 'requester_id' field has been set, false otherwise.
      */
    public boolean hasRequesterId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requester_id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearRequesterId() {
      requester_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setId(java.lang.String value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setDescription(java.lang.String value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'description_identifier' field.
      * @return The value.
      */
    public java.lang.String getDescriptionIdentifier() {
      return description_identifier;
    }

    /**
      * Sets the value of the 'description_identifier' field.
      * @param value The value of 'description_identifier'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setDescriptionIdentifier(java.lang.String value) {
      validate(fields()[3], value);
      this.description_identifier = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'description_identifier' field has been set.
      * @return True if the 'description_identifier' field has been set, false otherwise.
      */
    public boolean hasDescriptionIdentifier() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'description_identifier' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearDescriptionIdentifier() {
      description_identifier = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'document_created_at' field.
      * @return The value.
      */
    public java.lang.String getDocumentCreatedAt() {
      return document_created_at;
    }

    /**
      * Sets the value of the 'document_created_at' field.
      * @param value The value of 'document_created_at'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setDocumentCreatedAt(java.lang.String value) {
      validate(fields()[4], value);
      this.document_created_at = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'document_created_at' field has been set.
      * @return True if the 'document_created_at' field has been set, false otherwise.
      */
    public boolean hasDocumentCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'document_created_at' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearDocumentCreatedAt() {
      document_created_at = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'description_values' field.
      * @return The value.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues getDescriptionValues() {
      return description_values;
    }

    /**
      * Sets the value of the 'description_values' field.
      * @param value The value of 'description_values'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setDescriptionValues(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues value) {
      validate(fields()[5], value);
      this.description_valuesBuilder = null;
      this.description_values = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'description_values' field has been set.
      * @return True if the 'description_values' field has been set, false otherwise.
      */
    public boolean hasDescriptionValues() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'description_values' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.Builder getDescriptionValuesBuilder() {
      if (description_valuesBuilder == null) {
        if (hasDescriptionValues()) {
          setDescriptionValuesBuilder(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.newBuilder(description_values));
        } else {
          setDescriptionValuesBuilder(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.newBuilder());
        }
      }
      return description_valuesBuilder;
    }

    /**
     * Sets the Builder instance for the 'description_values' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setDescriptionValuesBuilder(uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues.Builder value) {
      clearDescriptionValues();
      description_valuesBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'description_values' field has an active Builder instance
     * @return True if the 'description_values' field has an active Builder instance
     */
    public boolean hasDescriptionValuesBuilder() {
      return description_valuesBuilder != null;
    }

    /**
      * Clears the value of the 'description_values' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearDescriptionValues() {
      description_values = null;
      description_valuesBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.String getLocation() {
      return location;
    }

    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setLocation(java.lang.String value) {
      validate(fields()[6], value);
      this.location = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearLocation() {
      location = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'document_size' field.
      * @return The value.
      */
    public java.lang.String getDocumentSize() {
      return document_size;
    }

    /**
      * Sets the value of the 'document_size' field.
      * @param value The value of 'document_size'.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder setDocumentSize(java.lang.String value) {
      validate(fields()[7], value);
      this.document_size = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'document_size' field has been set.
      * @return True if the 'document_size' field has been set, false otherwise.
      */
    public boolean hasDocumentSize() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'document_size' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.document.generator.core.document.models.DocumentGenerationCompleted.Builder clearDocumentSize() {
      document_size = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public DocumentGenerationCompleted build() {
      try {
        DocumentGenerationCompleted record = new DocumentGenerationCompleted();
        record.requester_id = fieldSetFlags()[0] ? this.requester_id : (java.lang.String) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.String) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.String) defaultValue(fields()[2]);
        record.description_identifier = fieldSetFlags()[3] ? this.description_identifier : (java.lang.String) defaultValue(fields()[3]);
        record.document_created_at = fieldSetFlags()[4] ? this.document_created_at : (java.lang.String) defaultValue(fields()[4]);
        if (description_valuesBuilder != null) {
          record.description_values = this.description_valuesBuilder.build();
        } else {
          record.description_values = fieldSetFlags()[5] ? this.description_values : (uk.gov.companieshouse.document.generator.core.document.models.DescriptionValues) defaultValue(fields()[5]);
        }
        record.location = fieldSetFlags()[6] ? this.location : (java.lang.String) defaultValue(fields()[6]);
        record.document_size = fieldSetFlags()[7] ? this.document_size : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
